#!/bin/bash

BASE_PATH=${MAGNETOMETER_BASE_PATH:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}
FILE_OWNER=${MAGNETOMETER_FILE_OWNER:-$(stat -c %U "$BASE_PATH")}
FILE_GROUP=$(id -gn "$FILE_OWNER")
export MAGNETOMETER_BASE_PATH="$BASE_PATH" MAGNETOMETER_FILE_OWNER="$FILE_OWNER"